### ISSUE TITLE
ESP flash tool instructions

### ISSUE THREAD

**Issue by jamine16** [OzInFl/WaveSentinelPublic---Squareline-Studio-UI-CC1101---ESP32#5]
For anybody not wanting to go through the build process, see the following link.
https://github.com/OzInFl/WaveSentinelPublic---Squareline-Studio-UI/discussions/4

**Comment by OzInFl** [comment]
There is also a web based flash utility, it has a bit more current build and there is a newer build that i havent published yet, but coming soon..

Here is the link: https://gtxpro.us/web-based-flash-utility/

**Comment by jamine16** [comment]
Thanks, i was having a lot of difficulty trying to flash the firmware  bin file directly.

The web based utility looks good.

**Comment by OzInFl** [comment]
Ill be releasing an update soon, trying to get some bugs worked out and making the capture replay work.. Glad the web based flasher helped.
