### ISSUE TITLE
I know this isnt github prob

### ISSUE THREAD

**Issue by shanejohn15** [OzInFl/WaveSentinelPublic---Squareline-Studio-UI-CC1101---ESP32#6]
But I had ordered a custom willy board from tindie.com and for some reason it's not letting me message you on there. Is there expected ship date

**Comment by OzInFl** [comment]
This is the tracking number, often times the post office that these are
dropped off to take forever to update the tracking info, your unit was
dropped off yesterday for shipping though, my wife personally dropped it
off. here is the tracking info for your reference: 9400111206204347310790

Thanks again!!

-T
