### ISSUE TITLE
The willy board

### ISSUE THREAD

**Issue by shanejohn15** [OzInFl/WaveSentinelPublic---Squareline-Studio-UI-CC1101---ESP32#7]
I got it, and got it hooked up to the tdisplay I just didn't solder the headers in because I wanted to make sure it worked before soldering, and it doesn't. It doesn't pick up signals or recognize the sd card, it shows that the jammer or sub ghz or ir goes into analyze like it's working but doesn't pick up or put out signals? Ive tested with the hackrf next to it. Is there something extra I need to do for the custom willy board to work with the willy firmware? Could it be the pins not being soldered in? I've moved the board around to try to make sure they were all making connection.. I'm not sure what I'm doing wrong or could it be defective? I'm lost lol and just want it to work..

**Comment by OzInFl** [comment]
Please be sure that you have all of the files for the willy firmware extracted to the SD card. You should have received a zip file with the contents for the SD card. Also be sure the switch is flipped up for SubGhz and Down for IR-Receive. IR-TX works regardless. BUT you must have all the files on the SD card prior to using the device!! that sounds like that may be your issue. Also I encourage you to hit the discord server.. much easier to support you there..

**Comment by shanejohn15** [comment]
Received sd files from the willy github or from getting sent the firmware after buying it? Like did the firmware creator have to send me an SD folder? Because I did download one off the github but it's only i.r. files yet I can't even get the universal i.r remote to do anything but look like the scanner in sub ghz.

**Comment by shanejohn15** [comment]
Sorry not universal, the only ir app I can click is learn but it doesn't pick up any signals just like sub ghz scanner

**Comment by OzInFl** [comment]
The Github repo for the files is here: https://github.com/h-RAT/Willy_Firmware_CC1101_ESP32_Display_Touchscreen/tree/main

Be sure to extract the assets folder to the SD card. Large SD cards wont work, if you dont see then little white screen that says transmitting 1/100 then 2/100, etc when you hit the universal remote and tv power for example, then something is not right with your setup. also not soldering at least some headers and just holding the display onto the connectors is likely to provide some unexpected results. Also ensure that if you are trying to capture IR then the switch must be down, up towards the ant connector for subghz as the firmware designed uses the same gpio pin in the firmware for both. All boards were tested as well, so its highly unlikely that the board has issues unless it got damaged in shipping. its really a pretty simple design actually. I suggest you come over to the discord server too as it may be easier to help you there!
